[package]
name = "bamboo-infrastructure-config"
version = "0.1.0"
edition = "2021"

[dependencies]
bamboo-application-tool-types = { path = "../bamboo-application-tool-types" }
bamboo-shared-types = { path = "../bamboo-shared-types" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = "1"
regex = "1"
dirs = "5"
tracing = "0.1"
aes-gcm = "0.10"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"

[dev-dependencies]
tempfile = "3"

[features]
test-utils = []
